main/urls.py
from unicodedata import name
from urllib.parse import urlparse
from django.urls import path

from . import views

app_name = "main"

urlpatterns = [
    path("", views.HomeView.as_view(), name="home"),
    path(
        "tracked-collections/",
        views.TrackedCollectionsView.as_view(),
        name="tracked-collections",
    ),
    path(
        "collection-stats/<str:collection_slug>",
        views.CollectionStatsView.as_view(),
        name="collection-stats",
    ),
    path(
        "collection-delete/<str:collection_slug>",
        views.delete_collection,
        name="collection-delete",
    ),
    path(
        "collection-txs/<str:collection_slug>",
        views.CollectionTransactionsView.as_view(),
        name="collection-txs",
    ),
]

tony_proj/urls.py
from django.contrib import admin
from django.urls import path, include
from main import views as main_views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("main.urls")),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html dir="ltr" lang="en">
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta
      name="keywords"
      content="wrappixel, admin dashboard, html css dashboard, web dashboard, bootstrap 5 admin, bootstrap 5, css3 dashboard, bootstrap 5 dashboard, Actappon dashboard, frontend, responsive bootstrap 5 admin template, Actappon admin lite design, Actappon admin lite dashboard bootstrap 5 dashboard template"
    />
    <meta
      name="description"
      content="Actappon Admin Lite Free Version is powerful and clean admin dashboard template, inpired from Bootstrap Framework"
    />
    <meta name="robots" content="noindex,nofollow" />
    <title>Tonys NFT Project</title>
    <!-- Favicon icon -->
    <link
      rel="icon"
      type="image/png"
      sizes="16x16"
      href="{% static 'main/assets/images/favicon.png' %}"
    />
    <!-- Custom CSS -->
    <link href="{% static 'main/assets/libs/flot/css/float-chart.css' %}" rel="stylesheet" />
    {% block css %}
    <!-- CSS here -->
    {% endblock css %}
    <!-- Custom CSS -->
    <link href="{% static 'main/dist/css/style.min.css' %}" rel="stylesheet" />
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>
    <!-- ============================================================== -->
    <!-- Preloader - style you can find in spinners.css -->
    <!-- ============================================================== -->
    <div class="preloader">
      <div class="lds-ripple">
        <div class="lds-pos"></div>
        <div class="lds-pos"></div>
      </div>
    </div>
    <!-- ============================================================== -->
    <!-- Main wrapper - style you can find in pages.scss -->
    <!-- ============================================================== -->
    <div
      id="main-wrapper"
      data-layout="vertical"
      data-navbarbg="skin5"
      data-sidebartype="full"
      data-sidebar-position="absolute"
      data-header-position="absolute"
      data-boxed-layout="full"
    >
      <!-- ============================================================== -->
      <!-- Topbar header - style you can find in pages.scss -->
      <!-- ============================================================== -->
      <header class="topbar" data-navbarbg="skin5">
        <nav class="navbar top-navbar navbar-expand-md navbar-dark">
          <div class="navbar-header" data-logobg="skin5">
            <!-- ============================================================== -->
            <!-- Logo -->
            <!-- ============================================================== -->
            <a class="navbar-brand" href="{% url 'main:home' %}">
              <!-- Logo icon -->
              <b class="logo-icon ps-2">
                <!--You can put here icon as well // <i class="wi wi-sunset"></i> //-->
                <!-- Dark Logo icon -->
                <!-- <img
                  src="{% static 'main/assets/images/logo-icon.png' %}"
                  alt="homepage"
                  class="light-logo"
                  width="25"
                /> -->
                <h1>Tonys</h1>
              </b>
              <!--End Logo icon -->
              <!-- Logo text -->
              <span class="logo-text ms-2">
                <!-- dark Logo text -->
                <!-- <img
                  src="{% static 'main/assets/images/logo-text.png' %}"
                  alt="homepage"
                  class="light-logo"
                /> -->
              </span>
              <!-- Logo icon -->
              <!-- <b class="logo-icon"> -->
              <!--You can put here icon as well // <i class="wi wi-sunset"></i> //-->
              <!-- Dark Logo icon -->
              <!-- <img src="{% static 'main/assets/images/logo-text.png" alt="homepage" class="light-logo" /> -->

              <!-- </b> -->
              <!--End Logo icon -->
            </a>
            <!-- ============================================================== -->
            <!-- End Logo -->
            <!-- ============================================================== -->
            <!-- ============================================================== -->
            <!-- Toggle which is visible on mobile only -->
            <!-- ============================================================== -->
            <a
              class="nav-toggler waves-effect waves-light d-block d-md-none"
              href="javascript:void(0)"
              ><i class="ti-menu ti-close"></i
            ></a>
          </div>
          <!-- ============================================================== -->
          <!-- End Logo -->
          <!-- ============================================================== -->
          <div
            class="navbar-collapse collapse"
            id="navbarSupportedContent"
            data-navbarbg="skin5"
          >
            <!-- ============================================================== -->
            <!-- toggle and nav items -->
            <!-- ============================================================== -->
            <!-- ALF Removed -->
            <!-- ============================================================== -->
            <!-- Right side toggle and nav items -->
            <!-- ============================================================== -->
          <!-- ALF Removed -->
        </div>
        </nav>
      </header>
      <!-- ============================================================== -->
      <!-- End Topbar header -->
      <!-- ============================================================== -->
      <!-- ============================================================== -->
      <!-- Left Sidebar - style you can find in sidebar.scss  -->
      <!-- ============================================================== -->
      <aside class="left-sidebar" data-sidebarbg="skin5">
        <!-- Sidebar scroll-->
        <div class="scroll-sidebar">
          <!-- Sidebar navigation-->
          <nav class="sidebar-nav">
            <ul id="sidebarnav" class="pt-4">
              <li class="sidebar-item">
                <a
                  class="sidebar-link waves-effect waves-dark sidebar-link"
                  href="{% url 'main:home' %}"
                  aria-expanded="false"
                  ><i class="mdi mdi-view-dashboard"></i
                  ><span class="hide-menu">Main</span></a
                >
              </li>
              <li class="sidebar-item">
                <a
                  class="sidebar-link waves-effect waves-dark sidebar-link"
                  href="{% url 'main:tracked-collections' %}"
                  aria-expanded="false"
                  ><i class="mdi mdi-chart-bar"></i
                  ><span class="hide-menu">Tracked Collections</span></a
                >
              </li>
              
            </ul>
          </nav>
          <!-- End Sidebar navigation -->
        </div>
        <!-- End Sidebar scroll-->
      </aside>
      <!-- ============================================================== -->
      <!-- End Left Sidebar - style you can find in sidebar.scss  -->
      <!-- ============================================================== -->
      <!-- ============================================================== -->
      <!-- Page wrapper  -->
      <!-- ============================================================== -->
      <div class="page-wrapper">
        <!-- ============================================================== -->
        <!-- Bread crumb and right sidebar toggle -->
        <!-- ============================================================== -->
        <div class="page-breadcrumb">
          <div class="row">
            <div class="col-12 d-flex no-block align-items-center">
              <h4 class="page-title">
                {% block title %}
                {% endblock title %}
              </h4>
              <!-- <div class="ms-auto text-end">
                <nav aria-label="breadcrumb">
                  <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="#">Home</a></li>
                    <li class="breadcrumb-item active" aria-current="page">
                      Library
                    </li>
                  </ol>
                </nav>
              </div> -->
            </div>
          </div>
        </div>
        <!-- ============================================================== -->
        <!-- End Bread crumb and right sidebar toggle -->
        <!-- ============================================================== -->
        <!-- ============================================================== -->
        <!-- Container fluid  -->
        <!-- ============================================================== -->
        <div class="container-fluid">
            {% block content %}
            <!-- CONTENT HERE -->
            {% endblock content %}
        </div>
        
        <!-- ============================================================== -->
        <!-- End Container fluid  -->
        <!-- ============================================================== -->
        <!-- ============================================================== -->
        <!-- footer -->
        <!-- ============================================================== -->
        <footer class="footer text-center fixed-bottom">
            © 2021 <a href="https://actappon.com">Actappon</a> Ltd. All rights reserved.
        </footer>
        <!-- ============================================================== -->
        <!-- End footer -->
        <!-- ============================================================== -->
      </div>
      <!-- ============================================================== -->
      <!-- End Page wrapper  -->
      <!-- ============================================================== -->
    </div>
    <!-- ============================================================== -->
    <!-- End Wrapper -->
    <!-- ============================================================== -->
    <!-- ============================================================== -->
    <!-- All Jquery -->
    <!-- ============================================================== -->
    <script src="{% static 'main/assets/libs/jquery/dist/jquery.min.js' %}"></script>
    <!-- Bootstrap tether Core JavaScript -->
    <script src="{% static 'main/assets/libs/bootstrap/dist/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'main/assets/libs/perfect-scrollbar/dist/perfect-scrollbar.jquery.min.js' %}"></script>
    <script src="{% static 'main/assets/extra-libs/sparkline/sparkline.js' %}"></script>
    <!--Wave Effects -->
    <script src="{% static 'main/dist/js/waves.js' %}"></script>
    <!--Menu sidebar -->
    <script src="{% static 'main/dist/js/sidebarmenu.js' %}"></script>
    <!--Custom JavaScript -->
    <script src="{% static 'main/dist/js/custom.min.js' %}"></script>
    <!-- Charts js Files -->
    <script src="{% static 'main/assets/libs/flot/excanvas.js' %}"></script>
    <script src="{% static 'main/assets/libs/flot/jquery.flot.js' %}"></script>
    <script src="{% static 'main/assets/libs/flot/jquery.flot.pie.js' %}"></script>
    <script src="{% static 'main/assets/libs/flot/jquery.flot.time.js' %}"></script>
    <script src="{% static 'main/assets/libs/flot/jquery.flot.stack.js' %}"></script>
    <script src="{% static 'main/assets/libs/flot/jquery.flot.crosshair.js' %}"></script>
    <script src="{% static 'main/assets/libs/flot.tooltip/js/jquery.flot.tooltip.min.js' %}"></script>
    <script src="{% static 'main/dist/js/pages/chart/chart-page-init.js' %}"></script>
    {% block js %}
    <!-- JS files here -->
    {% endblock js %}
  </body>
</html>